name: tests

on:
  push:
  pull_request:

jobs:
  test:
    runs_on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: taskdb
          POSTGRES_user: taskuser
          POSTGRES_PASSWORD: taskpass
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U taskuser -d taskdb"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DJANGO_SETTINGS_MODULE: config.settings.dev
      SECRET_KEY: ci-secret
      DEBUG: "0"
      ALLOWED_HOSTS: localhost,127.0.0.1

      DB_NAME: taskdb
      DB_USER: taskuser
      DB_PASSWORD: taskpass
      DB_HOST: 127.0.0.1
      DB_PORT: 5432

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
        
      - name: Install dependencies
        run: |
          python -m pip install  --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-django pytest-cov

      - name: Run migrations
        run: |
          python manage.py migrate

      - name: Run tests
        run: |
          pytest --cov=. --cov-report=term-missing